description: ITProTV’s engineers are facing challenges with optimism daily while working on ITProTV’s entirely custom-built site. See what’s happening in the engine room.
permalink: pretty
google_analytics: UA-43313614-13
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
repository: EdutainmentLIVE/edutainmentlive.github.io
theme: jekyll-theme-cayman
title: Tales from the Engine Room | ITProTV’s Engineering Blog
titles_from_headings:
  collections: true
  strip_title: true
